### ISSUE TITLE
When querying in cytoscape an error appears regarding an old STRING network.

### ISSUE THREAD

**Issue by bio-bean** [RBVI/stringApp#17]
The dialogue box asks if you want to update, clicking okay leads to another dialogue box which says 'requery network' with a red stop sign. The only option is to click close, unsure if this solves the issue.

**Comment by scaramonche** [comment]
Hi, can you please write which version of Cytoscape and the stringApp you are using and if you query in a Cytoscape session with already existing STRING networks which was saved some time ago.
Thanks, Nadya

**Comment by bio-bean** [comment]
Hi, I'm using Cytoscape 3.7.2 and stringApp 1.5.1. 
I don't think I'm using an old STRING network, I only installed cytoscape on this machine a few days ago. Thanks!

**Comment by scaramonche** [comment]
Hi, there has been a new release of Cytoscape, version 3.8.0. So, you could give that a try. The error you encountered should *only* happen, if you have opened an older Cytoscape session, which contains networks retrieved with the stringApp from STRING v10.5. Since the current STRING version is 11, the v10.5 and v11 networks are not compatible with each other. Could you try to open Cytoscape and make sure you have *no* networks loaded and then try to import a new network using either the STRING: protein query or the STRING: diseases query. 
Best, Nadya
