### ISSUE TITLE
"string show enrichment" toggle is hard to use

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/stringApp#20]
Half the time, this function does the wrong thing and the user is left thinking that they didn't get any enrichment results.  

Can we make separate show/hide functions instead of a toggle? Or just make show "always show" and ditch the hide altogether (I never actually want to hide the tab)

**Comment by scaramonche** [comment]
Thanks for reporting it, Alex! 
I have been working on fixing this in the last two weeks. It turned out to be a mixture of small things that got in the way of each other. I think I managed to fix it by keeping the show/hide option, but still testing a few things... We will release an update with this fix soon and I will update you once I am happy with the fix and you are very welcome to test it.

**Comment by scaramonche** [comment]
Hi Alex, did this improve with the 1.7.1 version? I definitely fixed some of the issues, but there might still be some things left. Could you please check and let me know?

**Comment by scaramonche** [comment]
Fixed in version 2.0.
