### ISSUE TITLE
Can't export Enrichment Results table

### ISSUE THREAD

**Issue by AlexanderPico** [RBVI/stringApp#4]
Not sure if this is a Cytoscape bug or an app bug... But the STRING Enrichment Results table is not available for export via File>Export>Table...  Tried right-click and even mulitselect copy/paste. Nothing worked. In the end, I recommended that they open up the CYS file and look in table/global.

Someone on helpdesk reported this originally: 
https://groups.google.com/forum/?hl=en_US%2F#!topic/cytoscape-helpdesk/Wi8r-8oUcu0

**Comment by scaramonche** [comment]
Somehow it is a mixture of both. The enrichment tables are not public, because if they are public, they appear in a tab called Unassigned tables. If they are private, as it is the case now, they can't be exported. My plan is to add an export button within the STRING Enrichment tab, just haven't done it yet. Do you have other ideas?

**Comment by scaramonche** [comment]
Enrichment export is available in the File -> Export menu in version 1.2.
